name: "Jai & Zach's Totally Amazing Food Journey"
favicon: null
layout_spectrum: 0.2877916027791798
typography_spectrum: 0.1028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49861750775016844
  lightness: 0.3535511752124876
  saturation: 0.48769061896018684
  rhythmicContrast: 0.5877239378169179
purpose: []
